export const ActionTypes = {
    SET_SYSTEM_PARAMETERS : "SET_SYSTEM_PARAMETERS",
    GET_SYSTEM_PARAMETERS : "GET_SYSTEM_PARAMETERS",
    CREATE_SYSTEM_PARAMETER : "CREATE_SYSTEM_PARAMETER",
    SELECT_SYSTEM_PARAMETER : "SELECT_SYSTEM_PARAMETER",
    UPDATE_SYSTEM_PARAMETER : "UPDATE_SYSTEM_PARAMETER",
    DELETE_SYSTEM_PARAMETER : "DELETE_SYSTEM_PARAMETER",

}